"""
Django settings for ereuse project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

# Production settings
from grd.conf.production_settings import *

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'weevjkzau7+&)$1p!3_eps(-4+*z%r8t=0+9zkj7*3u5yn681%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

TEMPLATE_DEBUG = True

ALLOWED_HOSTS = []

ROOT_URLCONF = 'ereuse.urls'

WSGI_APPLICATION = 'ereuse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'ereuse',
        'USER': 'ereuse',
        'PASSWORD': 'ereuse',
    }
}


# django-jenkins settings

INSTALLED_APPS += (
    'django_jenkins',
)

PROJECT_APPS = (
    'grd',
)

JENKINS_TASKS = (
    'django_jenkins.tasks.run_pep8',
    'django_jenkins.tasks.run_pyflakes',
#    'django_jenkins.tasks.run_jslint',
#    'django_jenkins.tasks.run_csslint',
#    'django_jenkins.tasks.run_sloccount'
)

try:
    from ereuse.local_settings import *
except ImportError as e:
    print("\033[1;41mException importing local_settings: %s\033[1;m" % e)
